-- Migration 020 - donor intelligence matrix (donor_intel + donor_source_seeds).
-- Source of truth for the donor-aware classifier (MUST 4 Compliant, PREFER 8
-- Partnership, program-area fit, eligibility routes) and the Donors page
-- (Donor Intelligence Mapping). Seeded from docs/donor_intel_matrix_app_ready.xlsx
-- via scripts/import_donor_intel.py. All flag columns are TEXT (yes/no/blank)
-- because BLANK means 'not documented' (unknown) -> never coerce to false.

create table if not exists donor_intel (
    id           bigserial primary key,
    donor                                  text,
    donor_short                            text,
    canonical_key text unique not null,
    aliases                                text,
    donor_category                         text,
    website                                text,
    ngo_eligible                           text,
    for_profit_eligible                    text,
    direct_local_org_eligible              text,
    govt_or_ccm_route_required             text,
    grant_route                            text,
    procurement_tender_route               text,
    loan_dev_finance_route                 text,
    subrecipient_partner_possible          text,
    open_call_unsolicited                  text,
    invitation_solicited                   text,
    two_stage_application                  text,
    online_portal_submission               text,
    active_route_status                    text,
    funding_scope_geographic               text,
    lmic_africa_focus                      text,
    global_multi_country_scope             text,
    priority_program_areas                 text,
    infectious_diseases_fit                text,
    hiv_aids_fit                           text,
    tb_fit                                 text,
    malaria_fit                            text,
    immunization_vaccines_fit              text,
    mnch_fit                               text,
    srhr_family_planning_fit               text,
    nutrition_fit                          text,
    ncds_fit                               text,
    hss_fit                                text,
    digital_health_data_ai_fit             text,
    education_fit                          text,
    economic_development_fit               text,
    climate_environment_fit                text,
    agriculture_food_security_fit          text,
    governance_equity_rights_fit           text,
    local_registration_required            text,
    local_board_required                   text,
    authorized_signatory_signoff_required  text,
    govt_endorsement_letter_required       text,
    tax_exempt_status_required             text,
    sam_uei_registration_required          text,
    prior_track_record_required            text,
    partnership_mandatory                  text,
    local_partner_required                 text,
    prefinance_required                    text,
    cost_sharing_match_required            text,
    audited_financials_required            text,
    ethics_irb_approval_required           text,
    concept_note_required                  text,
    full_technical_proposal_required       text,
    detailed_budget_required               text,
    budget_narrative_required              text,
    logframe_results_framework_required    text,
    theory_of_change_required              text,
    workplan_timeline_required             text,
    mande_plan_required                    text,
    cvs_key_personnel_required             text,
    org_capacity_statement_required        text,
    letters_of_support_required            text,
    partner_mou_required                   text,
    registration_certificate_required      text,
    bank_details_required                  text,
    due_diligence_questionnaire_required   text,
    safeguarding_policy_required           text,
    data_management_plan_required          text,
    risk_management_plan_required          text,
    sustainability_exit_plan_required      text,
    gender_inclusion_plan_required         text,
    environmental_safeguard_required       text,
    procurement_plan_required              text,
    org_chart_staffing_required            text,
    audit_report_required                  text,
    references_required                    text,
    award_low_usd                          text,
    award_high_usd                         text,
    total_annual_funding_global            text,
    funding_mechanism                      text,
    verification_level                     text,
    verification_caveats                   text,
    evidence_summary                       text,
    notes                                  text,
    source_urls                            text,
    updated_at   timestamptz not null default now()
);
create index if not exists donor_intel_short_idx on donor_intel(donor_short);
create index if not exists donor_intel_category_idx on donor_intel(donor_category);

-- Structured scrape-seed URLs (one donor -> many URLs). Feeds the scanner.
create table if not exists donor_source_seeds (
    id          bigserial primary key,
    donor       text not null,
    url         text not null,
    source_type text,
    created_at  timestamptz not null default now(),
    unique (donor, url)
);

